movie_module.movie_awards.*:
  type: config_entity
  label: Movie Awards
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    year:
      type: integer
      label: year
    movie:
      type: entity_reference
      label: Movie
      target_type: node
      handler: default:node
      targer_bundles: { movie: movie}    
